# Generated by Django 4.2 on 2025-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formularze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=255)),
                ('attr_name', models.CharField(max_length=255)),
                ('attr_value', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'formularze',
            },
        ),
        migrations.CreateModel(
            name='Szablony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, unique=True)),
                ('template_text', models.TextField()),
            ],
            options={
                'db_table': 'szablony',
            },
        ),
        migrations.AddIndex(
            model_name='formularze',
            index=models.Index(fields=['form_name', 'position'], name='formularze_form_na_4697ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formularze',
            unique_together={('form_name', 'attr_name')},
        ),
    ]
